artifact_paths = ["{repo}/design"]
exclude_artifact_paths = []
code_paths = [
    "{repo}/src",
    # "{repo}/design",
    # "{repo}/web-ui/src",
    # "{repo}/web-ui/tests",
    # "{repo}/web-ui/sel_tests",
]
exclude_code_paths = [
]
file_type = "markdown"
